name: elasticsearch-proxy
description: 'Elasticsearch Proxy'
version: 0.0.1
appVersion: "0.0.1"
home: https://github.com/novomatic-tech/elasticsearch-proxy
icon: https://static-www.elastic.co/assets/blteb1c97719574938d/logo-elastic-elasticsearch-lt.svg
sources:
  - https://github.com/novomatic-tech/elasticsearch-proxy
maintainers:
  - name: Tomasz Noco≈Ñ
    email: thom.nocon@gmail.com
  - name: Marek Chmiel
    email: marochm@gmail.com